language: node_js
node_js: "14.8.0"
sudo: required
cache:
  directories:
  - node_modules/

addons:
  chrome: stable


before_install:
  - npm install -g @angular/cli@10.0.5

install:
  - npm install
  
script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - ng build --prod

deploy:
- provider: script
  skip_cleanup: true
  script: >-
      curl -s -X POST -H "Content-Type: application/json" -H "Accept: application/json" -H "Travis-API-Version: 3" -H "Authorization: token $token" https://api.travis-ci.com/repo/ant-media%2FManagementConsole_WebApp/requests
  on:
    tags: true
    branch: master